### ISSUE TITLE
Investigate custom field plugins

### ISSUE THREAD

**Issue by eric-michel** [pressden/emma#40]
look at `field manager`, `piklist`, and `typerocket`

assess for ease-of-use, performance, size, and look/feel

**Comment by dswebsme** [comment]
Some quick notes regarding PikList and TypeRocket

**Piklist:**
```This plugin hasn't been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.```

- A full blown WP framework (much more than just custom fields)
- 2.2 MB
- Pretty dated code structure (PHP 5.x / no namespacing)
- Relatively flat structure (i.e. less cumbersome learning curve)

**TypeRocket**

- A full blown WP framework (much more than just custom fields)
- Heavy reliance on Composer (PHP Package Management … can be heavy sometimes)
- 3.2 MB
- Modern PHP 7 style code base
- A lot of behind the scenes magic (i.e. higher learning curve and more digging when debugging)

Based on what I’m seeing from both of these I feel like they will end up being overkill for Emma. 

Since we’re both on the same page that anything custom we put in Emma should be disabled by default (i.e. Custom Post Types / Taxonomies) I don't see a strong use case for a framework. Both could certainly be viable options for complex development in a child theme though.

**Comment by dswebsme** [comment]
WordPress Fieldmanager is now in Emma and loaded via an action that can easily be removed in a child theme as needed.

```add_action( 'after_setup_theme', 'emma_require_fieldmanager' );```
