### ISSUE TITLE
Style WooCommerce standard "My Account" page

### ISSUE THREAD

**Issue by dswebsme** [pressden/emma#97]
One of the default pages you have the option of creating when activating WooCommerce is the "My Account" page which is somewhat of a `Account Dashboard` page for customers (see wc-my-account-page.png attached). This is all built right into WooCommerce allowing users to manage their profile, view orders, manage addresses and payment methods, etc.

Currently, the login form and "My Account" features all work right out of the box with Emma but the screens all lack some of the default styling we've applied to other pages. A couple of examples:

- The sidebar menu should inherit our minimal `nav` styling. Currently the menu displays as a bulleted list.
- ~~The login form is super wide. The container might benefit by being narrowed on larger screens.~~
- Misc cleanup that makes sense on any of the internal `Dashboard` pages.

![wc-login](https://user-images.githubusercontent.com/9062957/93023009-2283b300-f5ba-11ea-94ca-c08475015705.png)
![wc-my-account-page](https://user-images.githubusercontent.com/9062957/93023010-2283b300-f5ba-11ea-822a-e98a26f7e2fe.png)

**Comment by eric-michel** [comment]
@dswebsme Hey Shaun! I'm working on some WC cleanup as we may have a site coming down the pipe soon. I'll be taking care of the super wide login form in my next PR. For the menu - do you just want the bullets gone and otherwise leave it the same? I'm not sure what our standard `nav` styles are for sidebars.

I did do some basic styling on each of these `my-account` endpoints, but they were definitely the last thing I touched, and the items I touched the least. If you have any other suggestions for endpoint format changes, let me know! One thing that definitely jumps out to me is making the `Order` and `Downloads` tables responsive, which they currently aren't.

**Comment by eric-michel** [comment]
#103 addresses the login form width

**Comment by eric-michel** [comment]
The list style on menu was fixed in a CSS cleanup PR
